# Generated by Django 3.2.12 on 2022-05-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftManagementApp', '0013_auto_20220519_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Next_month_open_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_status', models.BooleanField(default=False, verbose_name='open_status')),
            ],
        ),
    ]
