# Generated by Django 3.2.12 on 2022-05-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftManagementApp', '0014_next_month_open_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Next_month_open_status',
        ),
    ]
