# Generated by Django 3.2.12 on 2022-05-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftManagementApp', '0015_delete_next_month_open_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='public',
            field=models.BooleanField(default=True, verbose_name='public'),
        ),
    ]
