# Generated by Django 3.2.12 on 2022-05-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftManagementApp', '0017_auto_20220526_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publish_range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Publish_shift_start', models.DateField(verbose_name='Publish_shift_start')),
                ('Publish_shift_end', models.DateField(verbose_name='Publish_shift_end')),
            ],
        ),
    ]
